### ISSUE TITLE
feat: re-arrange app

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/nr-spar-data#15]
Via @abschwenker:

```
Approach: Create reusable pattern for Cron job in OpenShift to run various scripts against ZoneB “THE” DB. Each environment will have it's own job Dev->Dev Test->Test Prod->Prod
- Work lead by Paulo (consult with Marcio+Richardo+Derek as need) to create job
- Derek to create the openshift deployment configs
- Marcio to receive output form Derek+Paulo to run scripts
- Derek to help spar create proper dev environment
- Derek to document pattern for all FDS products going forward
- ??? to provide higher-level documentation
```

**Comment by paulushcgcj** [comment]
So far, we created an initial cronjob deployment file that deploys the docker image to run the ETL. It is already using the expected image.

@DerekRoberts can guide @marcionemec-daitan  on setting an imagestream to speed up the image loading? 

Next steps

- [ ] @marcionemec-daitan to keep working on making the code connect to postgres and oracle and execute a simple select
- [ ] @marcionemec-daitan to check if he has any issues with the SSL connection to oracle [Use the common folder on nr-forest-client as reference on how to get the .pem/der file](https://github.com/bcgov/nr-forest-client/tree/main/common)
- [ ] @DerekRoberts to sort out the proper moment to deploy/execute the ETL with team spar
- [ ] @DerekRoberts to document the cronjob pattern to leverage future migrations

**Comment by DerekRoberts** [comment]
Replaced by other issues.

https://github.com/bcgov/nr-spar-data/issues/25
https://github.com/bcgov/nr-spar-data/issues/26
https://github.com/bcgov/nr-spar-data/issues/27
https://github.com/bcgov/nr-spar-data/issues/28
