### ISSUE TITLE
chore: verify Oracle SSL connection

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/nr-spar-data#26]
Via @paulushcgcj:
`@marcionemec-daitan to check if he has any issues with the SSL connection to oracle [Use the common folder on nr-forest-client as reference on how to get the .pem/der file](https://github.com/bcgov/nr-forest-client/tree/main/common)`

**Comment by marcionemec-daitan** [comment]
Hi @DerekRoberts , I think we can close this issue, as it was already attended by #50 and #51 tasks.
